### ISSUE TITLE
help with bootloader and firmware installation

### ISSUE THREAD

**Issue by neokree** [yumagulovrn/dao-choc-ble#8]
Hello! 

A month ago I found out this project and I started to look for split keyboards. 
I really liked this one, but since I didn't find any store for it I decided to build it myself (maybe I should have looked at the russian telegram channel instead of the international one).
Anyway, now that I have received everything (except battery) and I soldered them together I would like to install the bootloader and firmware but I don't know how to do it. 

When I connect the keyboard to the pc it doesn't do anything (it should flash one of the two leds?) 
I saw in https://github.com/yumagulovrn/Adafruit_nRF52_Bootloader repo that it should enter DFU if I click the reset button two times, and maybe from that mode I should be able to see an USB drive that I could use to install the firmware? I tried multiple times but my macbook can't recognize it

Can you help me understand what's wrong? 
I don't know if I should check for electric soldering or I just don't get how to install the bootloader

**Comment by neokree** [comment]
Oh also when I bought the nRF52840 from MINEW on Aliexpress they asked me which configuration I wanted.
![U33f4b7e1e21e43c2871e88d1253d6df2r copia](https://user-images.githubusercontent.com/9344184/169706096-e719b292-8e46-4bdf-8890-db2b0dcb12bd.png)
I choose the first configuration from this list, since it was the only one that supported USB & power supply.

**Comment by yumagulovrn** [comment]
Hi!

Looks like I've completely forgot to mention bootloader in the repo, sorry :(

Long story short: you'll need a separate programmer ( J-Link or ST-Link or the Bluepill board or Raspberry Pi) to flash a bootloader, because MINEW chips are shipped without Adafruit bootloader preinstalled.

Relevant instructions can be found here https://github.com/joric/nrfmicro/wiki/Bootloader
But there are small differences:
* You should connect your PC only to programmer, and you'll need to connect all four contacts (power, ground. swd, swc) from programmer to Dao instead of only two in the instructions.
* You shound use bootloader file from https://github.com/yumagulovrn/Adafruit_nRF52_Bootloader/releases/tag/0.6.2-dao

If everything is done correctly, you will be able to flash Dao firmware via USB.

I'll add more detailed instructions next week

**Comment by neokree** [comment]
Thank you for your fast response! 

No problem for the instructions, I was more worried that I could have bricked the board 😓 
It's my first time soldering, normally I work with software hehe

I will buy a programmer and try to install the bootloader

**Comment by neokree** [comment]
Hello @yumagulovrn! After two order on Aliexpress today I finally received my J-Link programmer 💪 

I followed the guide here: https://github.com/Ladniy/jiran-ble-lite/wiki/Firmware, which was super helpful, thank you

I flashed the .hex file using JFlashLite and showed "Completed"..
But now I'm stuck at installing the firmware, I have tried multiple times to double press the reset button after connecting the USB-C directly to my macbook but it doesn't mount a new device. 
The blue led, which was blinking when connected with the J-Link programmer, it's completely off, even if I put the switch to ON. 

Is there anything that It seems wrong to you? Any help is welcomed
